-- MySQL Script generated by MySQL Workbench
-- Sat Jun 15 00:25:58 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema itech_heaven
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema itech_heaven
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `itech_heaven` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `itech_heaven` ;

-- -----------------------------------------------------
-- Table `itech_heaven`.`accessory_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itech_heaven`.`accessory_categories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `accessory_category_description` VARCHAR(255) NULL DEFAULT NULL,
  `accessory_category_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `itech_heaven`.`sales`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itech_heaven`.`sales` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `discount` DOUBLE NOT NULL,
  `sale_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 2
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `itech_heaven`.`accessories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itech_heaven`.`accessories` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `color` VARCHAR(255) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `feature` VARCHAR(255) NULL DEFAULT NULL,
  `material` VARCHAR(255) NULL DEFAULT NULL,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `accessory_category_id` INT NULL DEFAULT NULL,
  `main_image` VARCHAR(255) NULL DEFAULT NULL,
  `price` DOUBLE NOT NULL,
  `quantity` INT NOT NULL,
  `sale_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKa0ophfk7rxnnpf4fdw2csbxtb` (`accessory_category_id` ASC) VISIBLE,
  INDEX `FKeqvtgp50lyy6ksinw49hslgaq` (`sale_id` ASC) VISIBLE,
  CONSTRAINT `FKa0ophfk7rxnnpf4fdw2csbxtb`
    FOREIGN KEY (`accessory_category_id`)
    REFERENCES `itech_heaven`.`accessory_categories` (`id`),
  CONSTRAINT `FKeqvtgp50lyy6ksinw49hslgaq`
    FOREIGN KEY (`sale_id`)
    REFERENCES `itech_heaven`.`sales` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `itech_heaven`.`accessory_images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itech_heaven`.`accessory_images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `accessory_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKi5uakvompmxtau5g2e4qwxycd` (`accessory_id` ASC) VISIBLE,
  CONSTRAINT `FKi5uakvompmxtau5g2e4qwxycd`
    FOREIGN KEY (`accessory_id`)
    REFERENCES `itech_heaven`.`accessories` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `itech_heaven`.`type_device`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itech_heaven`.`type_device` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `type_device_description` VARCHAR(255) NULL DEFAULT NULL,
  `type_name` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `itech_heaven`.`devices`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itech_heaven`.`devices` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cpu` VARCHAR(255) NULL DEFAULT NULL,
  `gpu` VARCHAR(255) NULL DEFAULT NULL,
  `hdd` VARCHAR(255) NULL DEFAULT NULL,
  `os` VARCHAR(255) NULL DEFAULT NULL,
  `ram` VARCHAR(255) NULL DEFAULT NULL,
  `rom` VARCHAR(255) NULL DEFAULT NULL,
  `sim` VARCHAR(255) NULL DEFAULT NULL,
  `battery` VARCHAR(255) NULL DEFAULT NULL,
  `camera` VARCHAR(255) NULL DEFAULT NULL,
  `color` VARCHAR(255) NULL DEFAULT NULL,
  `date_release` DATE NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  `front_camera` VARCHAR(255) NULL DEFAULT NULL,
  `main_image` VARCHAR(255) NULL DEFAULT NULL,
  `material` VARCHAR(255) NULL DEFAULT NULL,
  `device_name` VARCHAR(255) NULL DEFAULT NULL,
  `origin` VARCHAR(255) NULL DEFAULT NULL,
  `price` DOUBLE NOT NULL,
  `quantity` INT NOT NULL,
  `screen` VARCHAR(255) NULL DEFAULT NULL,
  `size` VARCHAR(255) NULL DEFAULT NULL,
  `weight` VARCHAR(255) NULL DEFAULT NULL,
  `sale_id` INT NULL DEFAULT NULL,
  `type_device_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKadl54h3sg51daypffa7jgpc1v` (`sale_id` ASC) VISIBLE,
  INDEX `FKdc6se2q4hlbfonoe2w9ikldp4` (`type_device_id` ASC) VISIBLE,
  CONSTRAINT `FKadl54h3sg51daypffa7jgpc1v`
    FOREIGN KEY (`sale_id`)
    REFERENCES `itech_heaven`.`sales` (`id`),
  CONSTRAINT `FKdc6se2q4hlbfonoe2w9ikldp4`
    FOREIGN KEY (`type_device_id`)
    REFERENCES `itech_heaven`.`type_device` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `itech_heaven`.`device_images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itech_heaven`.`device_images` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `device_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK3rwwjtbx4cy0w06s90ie9l0fc` (`device_id` ASC) VISIBLE,
  CONSTRAINT `FK3rwwjtbx4cy0w06s90ie9l0fc`
    FOREIGN KEY (`device_id`)
    REFERENCES `itech_heaven`.`devices` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `itech_heaven`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itech_heaven`.`users` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `email` VARCHAR(255) NULL DEFAULT NULL,
  `firstname` VARCHAR(255) NULL DEFAULT NULL,
  `gender` BIT(1) NOT NULL,
  `lastname` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `phone` VARCHAR(255) NULL DEFAULT NULL,
  `provider` VARCHAR(255) NULL DEFAULT NULL,
  `username` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 30
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `itech_heaven`.`feedbacks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itech_heaven`.`feedbacks` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(255) NULL DEFAULT NULL,
  `feedback_date` DATE NULL DEFAULT NULL,
  `device_id` INT NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKrom1a3hagfup10skfpy0qyman` (`device_id` ASC) VISIBLE,
  INDEX `FK312drfl5lquu37mu4trk8jkwx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK312drfl5lquu37mu4trk8jkwx`
    FOREIGN KEY (`user_id`)
    REFERENCES `itech_heaven`.`users` (`id`),
  CONSTRAINT `FKrom1a3hagfup10skfpy0qyman`
    FOREIGN KEY (`device_id`)
    REFERENCES `itech_heaven`.`devices` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `itech_heaven`.`news`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itech_heaven`.`news` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `content` VARCHAR(255) NULL DEFAULT NULL,
  `image` VARCHAR(255) NULL DEFAULT NULL,
  `title` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `itech_heaven`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itech_heaven`.`orders` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `address_receiver` VARCHAR(255) NULL DEFAULT NULL,
  `date` DATE NULL DEFAULT NULL,
  `name_receiver` VARCHAR(255) NULL DEFAULT NULL,
  `phone_receiver` VARCHAR(255) NULL DEFAULT NULL,
  `status` VARCHAR(255) NULL DEFAULT NULL,
  `total_money` DOUBLE NOT NULL,
  `user_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK32ql8ubntj5uh44ph9659tiih` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK32ql8ubntj5uh44ph9659tiih`
    FOREIGN KEY (`user_id`)
    REFERENCES `itech_heaven`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `itech_heaven`.`order_details`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itech_heaven`.`order_details` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NOT NULL,
  `sell_price` DOUBLE NULL DEFAULT NULL,
  `device_id` INT NULL DEFAULT NULL,
  `order_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FKco9def3o34jl5uu92679hqlng` (`device_id` ASC) VISIBLE,
  INDEX `FKjyu2qbqt8gnvno9oe9j2s2ldk` (`order_id` ASC) VISIBLE,
  CONSTRAINT `FKco9def3o34jl5uu92679hqlng`
    FOREIGN KEY (`device_id`)
    REFERENCES `itech_heaven`.`devices` (`id`),
  CONSTRAINT `FKjyu2qbqt8gnvno9oe9j2s2ldk`
    FOREIGN KEY (`order_id`)
    REFERENCES `itech_heaven`.`orders` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `itech_heaven`.`password_reset_token`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itech_heaven`.`password_reset_token` (
  `id` BIGINT NOT NULL AUTO_INCREMENT,
  `expiry_date` DATETIME(6) NULL DEFAULT NULL,
  `token` VARCHAR(255) NULL DEFAULT NULL,
  `user_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `UKf90ivichjaokvmovxpnlm5nin` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FK83nsrttkwkb6ym0anu051mtxn`
    FOREIGN KEY (`user_id`)
    REFERENCES `itech_heaven`.`users` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `itech_heaven`.`permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itech_heaven`.`permission` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `url` VARCHAR(255) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 24
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `itech_heaven`.`persistent_logins`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itech_heaven`.`persistent_logins` (
  `username` VARCHAR(255) NOT NULL,
  `series` VARCHAR(255) NOT NULL,
  `token` VARCHAR(255) NOT NULL,
  `last_used` TIMESTAMP NOT NULL,
  PRIMARY KEY (`series`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `itech_heaven`.`role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itech_heaven`.`role` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL DEFAULT NULL,
  `description` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 7
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `itech_heaven`.`role_permission`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itech_heaven`.`role_permission` (
  `role_id` INT NOT NULL,
  `permission_id` INT NOT NULL,
  INDEX `FKf8yllw1ecvwqy3ehyxawqa1qp` (`permission_id` ASC) VISIBLE,
  INDEX `FKa6jx8n8xkesmjmv6jqug6bg68` (`role_id` ASC) VISIBLE,
  CONSTRAINT `FKa6jx8n8xkesmjmv6jqug6bg68`
    FOREIGN KEY (`role_id`)
    REFERENCES `itech_heaven`.`role` (`id`),
  CONSTRAINT `FKf8yllw1ecvwqy3ehyxawqa1qp`
    FOREIGN KEY (`permission_id`)
    REFERENCES `itech_heaven`.`permission` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `itech_heaven`.`type_device_accessory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itech_heaven`.`type_device_accessory` (
  `type_device_id` INT NOT NULL,
  `accessory_id` INT NOT NULL,
  INDEX `FK5xyo2x16ldkb9gekl9ok7aybf` (`accessory_id` ASC) VISIBLE,
  INDEX `FK6y1kvlqfpn9qqyj73gi78cuks` (`type_device_id` ASC) VISIBLE,
  CONSTRAINT `FK5xyo2x16ldkb9gekl9ok7aybf`
    FOREIGN KEY (`accessory_id`)
    REFERENCES `itech_heaven`.`accessories` (`id`),
  CONSTRAINT `FK6y1kvlqfpn9qqyj73gi78cuks`
    FOREIGN KEY (`type_device_id`)
    REFERENCES `itech_heaven`.`type_device` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `itech_heaven`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `itech_heaven`.`user_role` (
  `user_id` INT NOT NULL,
  `role_id` INT NOT NULL,
  INDEX `FKa68196081fvovjhkek5m97n3y` (`role_id` ASC) VISIBLE,
  INDEX `FKj345gk1bovqvfame88rcx7yyx` (`user_id` ASC) VISIBLE,
  CONSTRAINT `FKa68196081fvovjhkek5m97n3y`
    FOREIGN KEY (`role_id`)
    REFERENCES `itech_heaven`.`role` (`id`),
  CONSTRAINT `FKj345gk1bovqvfame88rcx7yyx`
    FOREIGN KEY (`user_id`)
    REFERENCES `itech_heaven`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
